package exceptionHandling;

public enum ExceptionList
{

    UNDEFINED_DATATYPE, AVOIDED_VARIABLE_NAME, EXIST_VARIABLE_NAME, NOT_INTEGER, NOT_LONG, NOT_DOUBLE, NOT_BOOLEAN, DECLARETION_ERROR, UNDEFINED_RESERVED_METHOD, UNEXPECTED_OPERATOR

}
